import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const clashGrotesk = localFont({
  src: [
    { path: '../public/fonts/ClashGrotesk-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../public/fonts/ClashGrotesk-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../public/fonts/ClashGrotesk-Semibold.woff2', weight: '600', style: 'normal' },
    { path: '../public/fonts/ClashGrotesk-Bold.woff2', weight: '700', style: 'normal' },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${clashGrotesk.className} dark:bg-background dark:text-white`}>{children}</body>
    </html>
  );
}
